config/routes.rb
Rails.application.routes.draw do
  resources :sons
  resources :fathers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/father.rb
class Father < ApplicationRecord
  has_many :sons, inverse_of: :father
  validates :f_name, presence: true
  accepts_nested_attributes_for :sons

  # This code below rejects child attribute for validation, but not saving into DB
  # accepts_nested_attributes_for :sons,
                    # reject_if: proc { |attributes| attributes['s_name'].blank? }

  def to_s
   f_name
  end
end

app/models/son.rb
class Son < ApplicationRecord
  belongs_to :father, inverse_of: :sons
  validates :s_name, presence: true, allow_blank: true

  def to_s
   s_name
  end
end
# class Son < ApplicationRecord
#   belongs_to :father, inverse_of: :sons
#   validates :s_name, presence: false  # works
#
# # validates :s_name, presence: true, allow_blank: true # this works too
  # validates :s_name, :presence => { :allow_blank => true } # this works
#
#   def to_s
#    s_name
#   end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fathers_controller.rb
class FathersController < ApplicationController
  before_action :set_father, only: [:show, :edit, :update, :destroy]

  # GET /fathers
  # GET /fathers.json
  def index
    @fathers = Father.all
  end

  # GET /fathers/1
  # GET /fathers/1.json
  def show
  end

  # GET /fathers/new
  def new
    @father = Father.new
    @father.sons.build
  end

  # GET /fathers/1/edit
  def edit
    @father.sons.build
  end

  # POST /fathers
  # POST /fathers.json
  def create
    @father = Father.new(father_params)

    respond_to do |format|
      if @father.save
        format.html { redirect_to @father, notice: 'Father was successfully created.' }
        format.json { render :show, status: :created, location: @father }
      else
        format.html { render :new }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fathers/1
  # PATCH/PUT /fathers/1.json
  def update
    respond_to do |format|
      if @father.update(father_params)
        format.html { redirect_to @father, notice: 'Father was successfully updated.' }
        format.json { render :show, status: :ok, location: @father }
      else
        format.html { render :edit }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fathers/1
  # DELETE /fathers/1.json
  def destroy
    @father.destroy
    respond_to do |format|
      format.html { redirect_to fathers_url, notice: 'Father was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_father
      @father = Father.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def father_params
      params.require(:father).permit(:f_name, sons_attributes: [:id, :s_name])
    end
end

app/controllers/sons_controller.rb
class SonsController < ApplicationController
  before_action :set_son, only: [:show, :edit, :update, :destroy]

  # GET /sons
  # GET /sons.json
  def index
    @sons = Son.all
  end

  # GET /sons/1
  # GET /sons/1.json
  def show
  end

  # GET /sons/new
  def new
    @son = Son.new
  end

  # GET /sons/1/edit
  def edit
  end

  # POST /sons
  # POST /sons.json
  def create
    @son = Son.new(son_params)

    respond_to do |format|
      if @son.save
        format.html { redirect_to @son, notice: 'Son was successfully created.' }
        format.json { render :show, status: :created, location: @son }
      else
        format.html { render :new }
        format.json { render json: @son.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sons/1
  # PATCH/PUT /sons/1.json
  def update
    respond_to do |format|
      if @son.update(son_params)
        format.html { redirect_to @son, notice: 'Son was successfully updated.' }
        format.json { render :show, status: :ok, location: @son }
      else
        format.html { render :edit }
        format.json { render json: @son.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sons/1
  # DELETE /sons/1.json
  def destroy
    @son.destroy
    respond_to do |format|
      format.html { redirect_to sons_url, notice: 'Son was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_son
      @son = Son.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def son_params
      params.require(:son).permit(:s_name, :father_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fathers_helper.rb
module FathersHelper
end

app/helpers/sons_helper.rb
module SonsHelper
end

app/views/fathers/_form.html.erb
<%= form_for(father) do |f| %>
<% if father.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(father.errors.count, "error") %>
        prohibited this father from being saved:</h2>

    <ul>
        <% father.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= f.label :f_name %>
    <%= f.text_field :f_name %>
</div>

<h2>Sons</h2>
<%= f.fields_for :sons do |sons| %>
<div class="sons_fields">
    <div class="field">
        <%= sons.label :s_name %><br>
        <%= sons.text_field :s_name %>
    </div>
</div>
<% end %>

<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/fathers/edit.html.erb
<h1>Editing Father</h1>

<%= render 'form', father: @father %>

<%= link_to 'Show', @father %> |
<%= link_to 'Back', fathers_path %>

app/views/fathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fathers</h1>

<table>
  <thead>
    <tr>
      <th>F name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fathers.each do |father| %>
      <tr>
        <td><%= father.f_name %></td>
        <td><%= link_to 'Show', father %></td>
        <td><%= link_to 'Edit', edit_father_path(father) %></td>
        <td><%= link_to 'Destroy', father, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Father', new_father_path %>

app/views/fathers/new.html.erb
<h1>New Father</h1>

<%= render 'form', father: @father %>

<%= link_to 'Back', fathers_path %>

app/views/fathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fathers name:</strong>
  <%= @father.f_name %>
</p>

<h2>Sons</h2>
<% if @father.sons.any? %>
<ul>
    <% @father.sons.each do |son| %>
    <li><%= link_to son.s_name, son %></li>
    <% end %>
</ul>
<% else %>
<p>none available</p>
<% end %>

<%= link_to 'Edit', edit_father_path(@father) %> |
<%= link_to 'Back', fathers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsNestedForms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/sons/_form.html.erb
<%= form_for(son) do |f| %>
  <% if son.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(son.errors.count, "error") %> prohibited this son from being saved:</h2>

      <ul>
      <% son.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :s_name %>
    <%= f.text_field :s_name %>
  </div>

  <div class="field">
    <%= f.label :father_id %>
    <%= f.text_field :father_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sons/edit.html.erb
<h1>Editing Son</h1>

<%= render 'form', son: @son %>

<%= link_to 'Show', @son %> |
<%= link_to 'Back', sons_path %>

app/views/sons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sons</h1>

<table>
  <thead>
    <tr>
      <th>S name</th>
      <th>Father</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sons.each do |son| %>
      <tr>
        <td><%= son.s_name %></td>
        <td><%= son.father %></td>
        <td><%= link_to 'Show', son %></td>
        <td><%= link_to 'Edit', edit_son_path(son) %></td>
        <td><%= link_to 'Destroy', son, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Son', new_son_path %>

app/views/sons/new.html.erb
<h1>New Son</h1>

<%= render 'form', son: @son %>

<%= link_to 'Back', sons_path %>

app/views/sons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>S name:</strong>
  <%= @son.s_name %>
</p>

<p>
  <strong>Father:</strong>
  <%= @son.father %>
</p>

<%= link_to 'Edit', edit_son_path(@son) %> |
<%= link_to 'Back', sons_path %>